PS C:\Users\dellpc\Downloads> cd LinuxTweetApp1
PS C:\Users\dellpc\Downloads\LinuxTweetApp1> docker build -t tweetapp .
[+] Building 176.3s (8/8) FINISHED
 => [internal] load build definition from Dockerfile                                                               1.1s
 => => transferring dockerfile: 194B                                                                               0.1s
 => [internal] load .dockerignore                                                                                  1.3s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/nginx:latest                                                    8.5s
 => [internal] load build context                                                                                  1.7s
 => => transferring context: 24.09kB                                                                               0.2s
 => [1/3] FROM docker.io/library/nginx:latest@sha256:0d17b565c37bcbd895e9d92315a05c1c3c9a29f762b011a10c54a66cd5  153.5s
 => => resolve docker.io/library/nginx:latest@sha256:0d17b565c37bcbd895e9d92315a05c1c3c9a29f762b011a10c54a66cd53c  0.7s
 => => sha256:0d17b565c37bcbd895e9d92315a05c1c3c9a29f762b011a10c54a66cd53c9b31 1.86kB / 1.86kB                     0.0s
 => => sha256:ee89b00528ff4f02f2405e4ee221743ebc3f8e8dd0bfd5c4c20a2fa2aaa7ede3 1.57kB / 1.57kB                     0.0s
 => => sha256:605c77e624ddb75e6110f997c58876baa13f8754486b461117934b24a9dc3a85 7.66kB / 7.66kB                     0.0s
 => => sha256:a9edb18cadd1336142d6567ebee31be2a03c0905eeefe26cb150de7b0fbc520b 25.35MB / 25.35MB                  16.6s
 => => sha256:589b7251471a3d5fe4daccdddfefa02bdc32ffcba0a6d6a2768bf2c401faf115 602B / 602B                         2.1s
 => => sha256:a2abf6c4d29d43a4bf9fbb769f524d0fb36a2edab49819c1bf3e76f409f953ea 31.36MB / 31.36MB                  19.1s
 => => sha256:186b1aaa4aa6c480e92fbd982ee7c08037ef85114fbed73dbb62503f24c1dd7d 894B / 894B                         3.4s
 => => sha256:b4df32aa5a72e2a4316aad3414508ccd907d87b4ad177abd7cbd62fa4dab2a2f 666B / 666B                         4.5s
 => => sha256:a0bcbecc962ed2552e817f45127ffb3d14be31642ef3548997f58ae054deb5b2 1.40kB / 1.40kB                     6.0s
 => => extracting sha256:a2abf6c4d29d43a4bf9fbb769f524d0fb36a2edab49819c1bf3e76f409f953ea                         81.1s
 => => extracting sha256:a9edb18cadd1336142d6567ebee31be2a03c0905eeefe26cb150de7b0fbc520b                         26.3s
 => => extracting sha256:589b7251471a3d5fe4daccdddfefa02bdc32ffcba0a6d6a2768bf2c401faf115                          0.0s
 => => extracting sha256:186b1aaa4aa6c480e92fbd982ee7c08037ef85114fbed73dbb62503f24c1dd7d                          0.0s
 => => extracting sha256:b4df32aa5a72e2a4316aad3414508ccd907d87b4ad177abd7cbd62fa4dab2a2f                          0.0s
 => => extracting sha256:a0bcbecc962ed2552e817f45127ffb3d14be31642ef3548997f58ae054deb5b2                          0.0s
 => [2/3] COPY index.html /usr/share/nginx/html                                                                    2.6s
 => [3/3] COPY linux.png /usr/share/nginx/html                                                                     2.6s
 => exporting to image                                                                                             4.4s
 => => exporting layers                                                                                            3.1s
 => => writing image sha256:eac49259b6d5aca159ffed6e3fd3e6aaabbeafae4941d76234cbd1f4b86c393f                       0.2s
 => => naming to docker.io/library/tweetapp                                                                        0.2s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
PS C:\Users\dellpc\Downloads\LinuxTweetApp1> docker run -dp 80:80 tweetapp
24bcb07c5b229728200336f8b17ec655332f8a8f211e19255a10a9ac96e8189c
PS C:\Users\dellpc\Downloads\LinuxTweetApp1> docker ps
CONTAINER ID   IMAGE      COMMAND                  CREATED          STATUS          PORTS                         NAMES
24bcb07c5b22   tweetapp   "/docker-entrypoint.…"   26 seconds ago   Up 14 seconds   0.0.0.0:80->80/tcp, 443/tcp   thirsty_chaum
PS C:\Users\dellpc\Downloads\LinuxTweetApp1> docker stop 24bcb07c5b22
24bcb07c5b22
PS C:\Users\dellpc\Downloads\LinuxTweetApp1> docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
PS C:\Users\dellpc\Downloads\LinuxTweetApp1> docker rm 24bcb07c5b22
24bcb07c5b22